spring:
  application:
    name: notification
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 30000
    virtual-host: ${RABBITMQ_VHOST:/}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED:true}
      validate-server-certificate: false
      verify-hostname: false

server:
  port: 8084

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking
